# nextcloud containers
name: cloud
services:

  nextcloud-db:
    image: mariadb:lts
    init: true
    restart: always
    networks:
      - cloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /tank/containers/nextcloud-db:/var/lib/mysql
    env_file:
      - ../default.env
      - db.env
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect" ]
      start_period: 10s
      interval: 10s
      timeout: 5s

  nextcloud-redis:
    image: redis:latest
    init: true
    restart: always
    networks:
      - cloud
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s

  nextcloud-cron:
    image: nextcloud:production
    init: true
    restart: always
    networks:
      - cloud
    volumes:
      - /tank/containers/nextcloud:/var/www/html
      - /tank/cloud/nextcloud/data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      nextcloud-db:
        condition: service_healthy
      nextcloud-redis:
        condition: service_healthy

  nextcloud:
    image: nextcloud:production
    init: true
    restart: always
    networks:
      - cloud
    volumes:
      - ./nextcloud-apache.conf:/etc/apache2/conf-enabled/nextcloud-apache.conf:ro
      - /tank/containers/nextcloud:/var/www/html
      - /tank/cloud/nextcloud/data:/var/www/html/data
      - /tank/cloud/video:/video:ro
      - /tank/cloud/music:/music
      - /tank/cloud/books:/books
      - /tank/cloud/comics:/comics
    env_file:
      - ../default.env
      - db.env
    environment:
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_TABLE_PREFIX='oc_'
    depends_on:
      nextcloud-db:
        condition: service_healthy
      nextcloud-redis:
        condition: service_healthy
      lldap:
        condition: service_healthy
      pocket-id:
        condition: service_healthy
    expose:
      - 80
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --show-error http://localhost/status.php | grep '\"installed\":true' || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 10
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.services.nextcloud.loadbalancer.sticky=true"
      - "traefik.http.middlewares.nextcloud-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-rep.redirectregex.permanent=true"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-rep,secure@file"
