# nextcloud containers
name: cloud
services:

  nextcloud-db:
    image: mariadb:lts
    init: true
    restart: always
    networks:
      - cloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /tank/containers/nextcloud-db:/var/lib/mysql
    env_file:
      - ../default.env
      - db.env

  nextcloud-redis:
    image: redis:latest
    init: true
    restart: always
    networks:
      - cloud

  nextcloud-cron:
    image: nextcloud:production
    init: true
    restart: always
    networks:
      - cloud
    volumes:
      - /tank/containers/nextcloud:/var/www/html
      - /tank/cloud/nextcloud/data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis

  nextcloud:
    image: nextcloud:production
    init: true
    restart: always
    networks:
      - cloud
    volumes:
      - ./nextcloud-apache.conf:/etc/apache2/conf-enabled/nextcloud-apache.conf:ro
      - /tank/containers/nextcloud:/var/www/html
      - /tank/cloud/nextcloud/data:/var/www/html/data
      - /tank/cloud/video:/video:ro
      - /tank/cloud/music:/music
      - /tank/cloud/books:/books
    env_file:
      - ../default.env
      - db.env
    environment:
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_TABLE_PREFIX='oc_'
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.services.nextcloud.loadbalancer.sticky=true"
      - "traefik.http.middlewares.nextcloud-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-rep.redirectregex.permanent=true"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-rep,secure@file"
