api:
  dashboard: true
  debug: true

log:
  level: INFO 

accessLog: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    http3: true
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/config.yaml"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@viggy96.me"
      storage: "/etc/traefik/acme.json"
      tlsChallenge: true

