api:
  dashboard: true
  debug: true

log:
  level: PANIC 

accessLog: {}

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/config.yaml"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@viggy96.me"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: http

