version: '3.7'

# dev containers
services:

  jenkins:
    build: 
      context: .
      network: host
    restart: always
    volumes:
      - /tank/container_data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=America/New_York
    expose:
      - 8080
      - 50000
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.viggy96.me`)"
      - "traefik.http.routers.jenkins.middlewares=secure@file"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
      - "com.centurylinklabs.watchtower.enable=false"

