version: '3.7'

# service containers
services:

  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro

  openldap:
    image: osixia/openldap:latest
    restart: always
    command: --copy-service
    networks:
      - default
      - cloud
      - media
    environment:
      - TZ=America/New_York
      - LDAP_TLS=false
      - LDAP_READONLY_USER=true
      - LDAP_ORGANISATION=box
      - LDAP_DOMAIN=viggy96.me
    volumes:
      - /tank/container_data/openldap/database:/var/lib/ldap
      - /tank/container_data/openldap/config:/etc/ldap/slapd.d
    expose:
       - 389

  traefik:
    image: traefik:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - default
      - cloud
      - media
    environment:
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/:/etc/traefik
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.viggy96.me`)"
      - "traefik.http.routers.traefik.middlewares=private@file"
      - "traefik.http.routers.traefik.service=api@internal"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    restart: always
    environment:
      - TZ=America/New_York
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.phpldapadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpldapadmin.rule=Host(`phpldapadmin.viggy96.me`)"
      - "traefik.http.routers.phpldapadmin.middlewares=private@file"

  www:
    image: viggy96/resume-website:latest
    restart: always
    environment:
      - ENV=production
      - PORT=443
    expose:
      - 443
    labels: 
      - "traefik.enable=true"
      - "traefik.http.services.www.loadbalancer.server.port=443"
      - "traefik.http.routers.www.rule=Host(`www.viggy96.me`)"
      - "traefik.http.routers.www.middlewares=secure@file"

  wireguard:
    image: weejewel/wg-easy:latest
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    volumes: 
      - /tank/container_data/wireguard:/etc/wireguard
    environment:
      - WG_HOST=wireguard.viggy96.me
      - WG_DEFAULT_DNS=192.168.1.1
    expose:
      - 51821
    ports:
      - 51820:51820/udp
    labels: 
      - "traefik.enable=true"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      - "traefik.http.routers.wireguard.rule=Host(`wireguard.viggy96.me`)"
      - "traefik.http.routers.wireguard.middlewares=private@file"


# external networks 
networks:

  cloud:
    external:
      name: cloud_default
      
  media:
    external:
      name: media_default

