version: '3.7'

# service containers
services:

  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro

  traefik:
    image: traefik:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - default
      - cloud
      - media
    environment:
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/:/etc/traefik
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.viggy96.me`)"
      - "traefik.http.routers.traefik.middlewares=private@file"
      - "traefik.http.routers.traefik.service=api@internal"

  www:
    image: viggy96/resume-website:latest
    restart: always
    environment:
      - ENV=production
    expose:
      - 443
    labels: 
      - "traefik.enable=true"
      - "traefik.http.services.www.loadbalancer.server.port=443"
      - "traefik.http.routers.www.rule=Host(`www.viggy96.me`)"
      - "traefik.http.middlewares.www-rep.redirectregex.regex=^https://viggy96.me/(.*)"
      - "traefik.http.middlewares.www-rep.redirectregex.replacement=https://www.viggy96.me/$${1}"
      - "traefik.http.middlewares.www-rep.redirectregex.permanent=true"
      - "traefik.http.routers.www.middlewares=www-rep,secure@file"

  wireguard:
    image: weejewel/wg-easy:latest
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes: 
      - /tank/container_data/wireguard:/etc/wireguard
    environment:
      - WG_HOST=wireguard.viggy96.me
      - WG_DEFAULT_DNS=192.168.1.1
    expose:
      - 51821
    ports:
      - 51820:51820/udp
    labels: 
      - "traefik.enable=true"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      - "traefik.http.routers.wireguard.rule=Host(`wireguard.viggy96.me`)"
      - "traefik.http.routers.wireguard.middlewares=private@file"


# external networks 
networks:

  cloud:
    external:
      name: cloud_default
      
  media:
    external:
      name: media_default

