version: '3.7'

# media containers
services:

  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: always
    environment:
      - UID=33
      - GID=33
      - TZ=America/Chicago
    devices:
      - /dev/dri
    volumes:
      - /tmp/jellyfin:/transcodes
      - /tank/container_data/jellyfin_config:/config
      - /tank/container_data/jellyfin_cache:/cache
      - /tank/cloud/videos:/media/video:ro
      - /tank/cloud/music:/media/music:ro
      - /tank/cloud/books:/media/books:ro
    expose:
      - 8096
    ports:
      - 1900:1900/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.viggy96.me`)"
      - "traefik.http.routers.jellyfin.middlewares=secure@file"

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: always
    environment:
      - PUID=33
      - PGID=33
      - UMASK=022
      - TZ=America/Chicago
      - WEBUI_PORT=8080
    volumes:
      - /tank/container_data/qbittorrent:/config
      - /tank/downloads:/downloads
    expose:
      - 8080
    ports:
      - 1080:1080/tcp
      - 1080:1080/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.viggy96.me`)"
      - "traefik.http.routers.qbittorrent.middlewares=private@file"

  nzbget:
    image: linuxserver/nzbget:latest
    restart: always
    environment:
      - PUID=33
      - PGID=33
      - UMASK=022
      - TZ=America/Chicago
    volumes:
      - /tank/container_data/nzbget:/config
      - /tank/downloads/nzbget:/downloads
    expose:
      - 6789
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.viggy96.me`)"
      - "traefik.http.routers.nzbget.middlewares=private@file"

  prowlarr:
    image: linuxserver/prowlarr:develop
    restart: always
    environment:
      - PUID=33
      - PGID=33
      - TZ=America/Chicago
    volumes:
      - /tank/container_data/prowlarr:/config
    expose:
      - 9696 
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.viggy96.me`)"
      - "traefik.http.routers.prowlarr.middlewares=private@file"

  sonarr:
    image: linuxserver/sonarr:latest
    restart: always
    environment:
      - PUID=33
      - PGID=33
      - TZ=America/Chicago
    volumes:
      - /tank/container_data/sonarr:/config
      - /tank/cloud/videos/TV:/tv
      - /tank/downloads:/downloads
    expose:
      - 8989
    depends_on:
      - qbittorrent
      - nzbget
      - prowlarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.viggy96.me`)"
      - "traefik.http.routers.sonarr.middlewares=private@file"

  radarr:
    image: linuxserver/radarr:latest
    restart: always
    environment:
      - PUID=33
      - PGID=33
      - TZ=America/Chicago
    volumes:
      - /tank/container_data/radarr:/config
      - /tank/cloud/videos/Movies:/movies
      - /tank/downloads:/downloads
    expose:
      - 7878
    depends_on:
      - qbittorrent
      - nzbget
      - prowlarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.rule=Host(`radarr.viggy96.me`)"
      - "traefik.http.routers.radarr.middlewares=private@file"

  bazarr:
    image: linuxserver/bazarr:latest
    restart: always
    environment:
      - PUID=33
      - PGID=33
      - TZ=America/Chicago
    volumes:
      - /tank/container_data/bazarr:/config
      - /tank/cloud/videos/TV:/tv
      - /tank/cloud/videos/Movies:/movies
    expose:
      - 6767
    depends_on:
      - sonarr
      - radarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.viggy96.me`)"
      - "traefik.http.routers.bazarr.middlewares=private@file"

  lidarr:
    image: linuxserver/lidarr:latest
    restart: always
    environment:
      - PUID=33
      - PGID=33
      - TZ=America/Chicago
    volumes:
      - /tank/container_data/lidarr:/config
      - /tank/cloud/music:/music
      - /tank/downloads:/downloads
    expose:
      - 8686
    depends_on:
      - qbittorrent
      - nzbget
      - prowlarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.viggy96.me`)"
      - "traefik.http.routers.lidarr.middlewares=private@file"

  readarr:
    image: linuxserver/readarr:nightly
    restart: always
    environment:
      - PUID=33
      - PGID=33
      - TZ=America/Chicago
    volumes:
      - /tank/container_data/readarr:/config
      - /tank/cloud/books:/books
      - /tank/downloads:/downloads
    expose:
      - 8787
    depends_on:
      - qbittorrent
      - nzbget
      - prowlarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.readarr.loadbalancer.server.port=8787"
      - "traefik.http.routers.readarr.rule=Host(`readarr.viggy96.me`)"
      - "traefik.http.routers.readarr.middlewares=private@file"

